[phases.setup]
nixPkgs = ["php82", "composer", "nodejs", "ffmpeg", "python311", "python311Packages.pip"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "python3 -m pip install yt-dlp"]
